### ISSUE TITLE
AES GCM mode requires special handling

### ISSUE THREAD

**Issue by vzsg** [vapor/crypto#16]
GCM is a mode for [authenticated encryption and decryption](https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption), which needs different input/output (ciphertext + auth tag) and special handling, unlike the other modes.

In its current state, the the `.gcm` method is useless, decryption will never succeed without the tag – which is currently _lost_ during encryption.

---

I can think of a few options to resolve this:
1. Remove `.gcm` as a supported mode completely.
 _(Simple, but barbaric.)_

1. Add a new interface for authenticated cyphers where the input/output is a tuple of `(ciphertext, tag)`, and move GCM there, implementing the flow as described at the link above.
_(Supporting Additional Auth Data might become possible too.)_

1. The auth tag could be appended to the ciphertext on encryption, and could be split from there for decryption. OpenSSL's default tag size is well known (~~12~~ 16 bytes). This should be documented, obviously.
_(This implies that the public interface would not change, and this crypto module could communicate with itself.)_

---

Also, [CipherTests](https://github.com/vapor/crypto/blob/master/Tests/CipherTests/CipherTests.swift) is a little lacking on the mode coverage, and really needs some tending.

**Comment by tannernelson** [comment]
@vzsg If the cipher/tag pattern is only supported by GCM it's hard to justify the creation of a whole new protocol
I like the idea of appending the tag to the text. Is there some character that we are sure won't appear in the encryption that would be easy to split by as well? If not, just lobbing off the last 12 bytes is easy. We could even make a helper for it.

My vote is for 3. Are there any options you like more than others?

**Comment by vzsg** [comment]
"Splitting" was a bad choice of words on my part, I actually meant appending without separator and lobbing off by count.

I'm leaning towards option 3 too. To me, this scheme is a workable compromise even if a caller wants to manipulate the tag separately. Which I think shouldn't really happen among the users of this ciphering _utility_.

---

Regarding option 2, there are other authenticated modes of operation, but only GCM is listed in the enum now. CCM also seems to be supported by CLibreSSL.

**Comment by tanner0101** [comment]
GCM has been removed in #23. This is open for someone to implement.
