### ISSUE TITLE
SHA256 hash is wrong for newlines

### ISSUE THREAD

**Issue by bennibau** [vapor/crypto#35]
When you try to hash a string which contains newlines
example:
`test\ntest`

the hash is different than the hash of this string (tried on different online hashing tools):
`test
test`
But since `String` does not support newlines in any other way than \n or \r\n or \r you are not able to produce the correct hash. This is important for Amazon AWS access because exactly that has is needed there.

**Comment by vzsg** [comment]
Have you figured it out?

**Comment by bennibau** [comment]
yes somehow not my hashes are correct. But the AWS request still is refused by the server because of invalid signature. That is strange because my canonical request and my string to sign are identical to the ones requested by aws
