### ISSUE TITLE
Add private/public key parsing for using with RSA

### ISSUE THREAD

**Issue by Andrewangeta** [vapor/crypto#42]
A convenience parser to make a pub/priv keyhole digestible by RSA alg.

**Essentially transforming this** 
`"-----BEGIN PRIVATE KEY-----\nQklCTElPR1JBUEhZ==\n-----END PRIVATE KEY-----\n"`

**Into this**
`QklCTElPR1JBUEhZ`

**Then base64 decoded into this**
`BIBLIOGRAPHY`

**Comment by vzsg** [comment]
Parsing a PEM-encoded private key is not _that_ simple, as the private key data is wrapped in an ASN.1 structure. But sure, having this feature would be definitely helpful.

**Comment by Andrewangeta** [comment]
@vzsg Is that you making an offer 🌚

**Comment by vzsg** [comment]
I've already implemented it with OpenSSL a few times for Vapor 2, but I don't have the slightest idea how to do it with AppleTLS 🤥

So this is just me acting smarta$$y.

**Comment by 0xTim** [comment]
The SwiftNIO stuff may change things, looks like it brings back OpenSSL

**Comment by vzsg** [comment]
Yeah, their support module pulls in LibreSSL on macOS and regular OpenSSL on Linux. That's not necessarily a bad thing :)

**Comment by tanner0101** [comment]
This will be fixed in RC.2. Thanks @Andrewangeta
