### ISSUE TITLE
Random Int max/min

### ISSUE THREAD

**Issue by mcdappdev** [vapor/crypto#56]
It would be great to make this function public: https://github.com/vapor/crypto/blob/master/Sources/Random/OSRandom.swift#L22

**Comment by tanner0101** [comment]
that should probably go on data generator itself so that all of them benefit from it

**Comment by bre7** [comment]
Will it be replaced by Swift 4.2's new random functions ?

**Comment by 0xTim** [comment]
@bre7 do you know if they'll work on Linux?

**Comment by bre7** [comment]
Haven't dld 4.2 yet but from the original proposal, I'd say so

**Comment by tanner0101** [comment]
This has been added in CryptoKit 4:

```swift
let rand = UInt8.random()
```

You can also do:
```swift
let rand = [UInt8].random(count: 1024)
```

Thanks!
