### ISSUE TITLE
Bcrypt verifyPassword not working

### ISSUE THREAD

**Issue by kylerokita** [vapor/crypto#7]
Trying to use bcrypt to hash passwords, but when I  ```verifyPassword``` it never returns true.

Steps to reproduce:

```
let password = "test123456"
let hash = try BCrypt.hashPassword(password)
let verify = try BCrypt.verifyPassword(password, matchesHash: hash)
print(verify) //false
```

**Comment by Joannis** [comment]
Not working anymore as of the 08-18 update of Vapor/Crypto. Before that I had it working
