### ISSUE TITLE
Could the IV be automatically extracted from the encrypted data?

### ISSUE THREAD

**Issue by backslash-f** [vapor/crypto#84]
More like a question.

So this works fine:

```swift
let data = "The black knight always triumphs!".convertToData()
let key = "01234567890123456789012345678901".convertToData()
let iv = try CryptoRandom().generateData(count: 16)
let encryptedData = try AES256CBC.encrypt(data, key: key, iv: iv)

let decryptedData = try AES256CBC.decrypt(encryptedData, key: key, iv: iv)
print(decryptedData.convert(to: String.self)) // The black knight always triumphs!
```

Question is can I *not* pass in the `iv` as argument so it could be automatically extracted from the encrypted data? As in:

```swift
let decryptedData = try AES256CBC.decrypt(encryptedData, key: key) <<--
print(decryptedData.convert(to: String.self))

Throws: ⚠️ [CryptoError.cipherIVSize: Invalid cipher IV length 0 != 16.]
```

I'm trying to avoid having to pass the IV around as in [here](https://github.com/backslash-f/aescryptable) (relies on Apple's `CommonCryto` / `CCCryptor`).

Thanks.

**Comment by vzsg** [comment]
No, but if you want, you could prepend the IV to the ciphertext, send/store them together, then split off the first 16 bytes when decrypting.

**Comment by backslash-f** [comment]
`you seem to be doing the same thing implicitly` <<-- exactly 🙃

All right, then. Thanks for confirming. 👍🏻
